# Generated by Django 6.0.7 on 2026-08-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_likes_alter_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
