version: '3.8'

services:
  web:
    build: .
    container_name: wagtail_web
    volumes:
      - ./:/app                    # монтируем всю папку проекта (база, медиа, код)
      - static_volume:/app/staticfiles   # статика для nginx
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: wagtail_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - ./media:/app/media:ro      # монтируем медиа напрямую, чтобы nginx читал
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume: