# Generated by Django 6.0.7 on 2026-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 баллов'), (2, '2 баллов'), (3, '3 баллов'), (4, '4 баллов'), (5, '5 баллов')], default=5, verbose_name='Оценка'),
        ),
    ]
