# Generated by Django 6.0.7 on 2026-08-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_service_calculatorsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorsettings',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=0, default=200000, max_digits=10, verbose_name='Стоимость дня работы'),
        ),
    ]
