"""
Django settings for _core project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from PIL import ImageFile



# Установка максимального качества и отключение оптимизации PNG при сохранении
# 0 — минимальное сжатие (максимальное качество и скорость сохранения)
# По умолчанию Pillow использует уровень 6
WAGTAILIMAGES_PNG_COMPRESSION_LEVEL = 0


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PROJECT_TITLE = "Дополненная реальность в вашем бизнесе"

SITE_ID = 1  # или ID твоего сайта в таблице sites

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rj#-z^kx3j+1ay397otg6j8m_8#v^$^$jys6&41vy^&6le)ezc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Безопасность
# SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-...')   # прочитаем из переменной окружения
# DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = ['ar-to-business.ru', '159.194.205.233', 'localhost', '127.0.0.1']


CSRF_TRUSTED_ORIGINS = ['https://ar-to-business.ru']
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_cleanup.apps.CleanupConfig',

    # My apps
    'a_home',
    'a_users',
    'a_blog',
    'comments',
    'pages',
    
    # Third party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_browser_reload',
    'django_htmx',

    # Wagtail
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.contrib.settings',
    'wagtail.contrib.sitemaps',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    'modelcluster',
    'taggit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]
if DEBUG:
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware']

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = '_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'a_home.cprocs.project_title',
                'wagtail.contrib.settings.context_processors.settings',
            ],
        },
    },
]

WSGI_APPLICATION = '_core.wsgi.application'


# Database
# База данных – теперь в /data внутри контейнера
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# MEDIA_URL = '/media/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' 

# Статика – будет в томе для nginx
STATIC_ROOT = '/app/staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'

AUTH_USER_MODEL = 'a_users.CustomUser'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Изменяем обратное имя связи для пользователей в Wagtail
WAGTAILIMAGES_IMAGE_MODEL = 'wagtailimages.Image'

SILENCED_SYSTEM_CHECKS = [
    'treebeard.E001',
]

WAGTAIL_SITE_NAME = 'AR Blog'
WAGTAILADMIN_BASE_URL = 'http://mywebsite.com'

# Отключает принудительное сжатие (по умолчанию 85)
WAGTAILIMAGES_JPEG_QUALITY = 100
WAGTAILIMAGES_WEBP_QUALITY = 100

# Разрешает загрузку изображений большого разрешения (по умолчанию 10000)
# WAGTAILIMAGES_MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # Лимит 50 МБ
WAGTAILIMAGES_MAX_UPLOAD_SIZE = 50 * 1440 * 1440


